# Generated by Django 4.2.6 on 2023-11-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentRecord', '0002_hostel_registration_hostel_allocation_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.IntegerField(max_length=15),
        ),
    ]
