# Generated by Django 4.2.6 on 2023-11-02 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentRecord', '0003_alter_student_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(15)]),
        ),
    ]
