# Generated by Django 4.2.6 on 2023-11-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentRecord', '0004_alter_student_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='admin_no',
            new_name='admission_no',
        ),
    ]
