# Generated by Django 4.2.6 on 2023-11-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentRecord', '0005_rename_admin_no_registration_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
