# Generated by Django 4.2.6 on 2023-11-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentRecord', '0006_alter_student_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='admission_no',
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
