# Generated by Django 4.2.6 on 2023-11-04 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studentRecord', '0007_remove_registration_admission_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
